### ISSUE TITLE
Final Push: Airports Checklist

### ISSUE THREAD

**Issue by danicrosby** [nss-evening-cohort-14/pan-am-group-project#8]
- [ ] VIEW all the airports PanAm can be hangered.
- [ ] ADD a new airport.
- [ ] EDIT an airport.
- [ ] DELETE an airport.
- [ ] SCREENSHOT
