### ISSUE TITLE
Final Push: Food Service Checklist

### ISSUE THREAD

**Issue by danicrosby** [nss-evening-cohort-14/pan-am-group-project#9]
- [ ] VIEW all the food options available for flights.
- [ ] ADD items to the menu.
- [ ] EDIT items on the menu.
- [ ] DELETE items on the menu.
- [ ] SCREENSHOT
